export const diagnosticsTools = [
  'list_pages',
  'select_page',
  'list_console_messages',
  'get_console_message',
  'list_network_requests',
  'get_network_request',
  'take_snapshot',
  'take_screenshot',
  'performance_start_trace',
  'performance_stop_trace',
  'performance_analyze_insight',
  'take_heapsnapshot',
  'get_heapsnapshot_summary',
  'get_heapsnapshot_details',
  'get_heapsnapshot_class_nodes',
  'get_heapsnapshot_retainers',
  'get_heapsnapshot_retaining_paths',
  'get_heapsnapshot_edges',
  'get_heapsnapshot_dominators',
  'compare_heapsnapshots',
  'get_heapsnapshot_duplicate_strings',
  'get_heapsnapshot_object_details',
  'query_heapsnapshot_objects',
  'close_heapsnapshot',
] as const
