export ZDOTDIR="${HOME}/.config/zsh"

[[ -f "${ZDOTDIR}/path.sh" ]] && source "${ZDOTDIR}/path.sh"

if [[ -f "${HOME}/.config/dev-setup/env.sh" ]]; then
  source "${HOME}/.config/dev-setup/env.sh"
fi
