// Stable advisory policy; never a live availability catalog or an execution override.
// Sources, benchmark versions, prices, and limitations: ../../README.md#model-routing-evidence.
export const SUBAGENT_MODEL_GUIDANCE = `Provider/model selection (advisory; configured auth, availability, and repository locks still apply):
- cliproxyapi / gpt-5.6-sol: preferred baseline for well-specified implementation, tests, refactors, routine debugging, and straightforward plans. Strong coding baseline with lower API token prices than Astra, but not proven cheaper per completed coding task or under subscriptions.
- cliproxyapi / gpt-6-astra: prefer for complex end-to-end implementation, difficult debugging, architecture/planning with many constraints, and demanding verification. Independent Codex benchmarks found higher coding scores at similar task cost to Sol through token efficiency; do not reserve Astra only for review. General reasoning gains and economics are mixed, so do not escalate every planning task automatically.
- xai / grok-4.6: strong alternative for implementation, terminal/tool-heavy tasks, research, and independent cross-provider review. Independent evaluations show improved agentic performance over 4.5 at unchanged uncached API token prices. Use for substantive work, not only fallback; require evidence and tests for review conclusions.
- xai / grok-4.5: fallback when 4.6 is unavailable, a retained-session continuation, or a measured cache-heavy workload favors it. Lower cached-input API pricing alone does not establish lower task cost, faster execution, or better subscription economics. Prefer 4.6 for new Grok assignments absent contrary evidence.
- Effort policy, not a benchmark-proven optimum: low for narrow reconnaissance; medium for bounded implementation and ordinary planning/debugging; high for complex work or demanding verification; xhigh/max only for justified escalation. The cited headline comparisons do not validate these exact role/effort combinations. Pi supports low/medium/high/xhigh/max for these cliproxyapi models, low/medium/high for Grok 4.5, and low/medium/high/xhigh for Grok 4.6.
- Prefer the configured subscription routes: cliproxyapi is the local Codex account pool; openai-codex is an explicitly chosen direct-subscription alternative, not another pool; xai supports Grok subscription OAuth. openai, openrouter, and API-key routes have separate billing and are not automatic subscription fallbacks. Verify auth rather than inferring subscription billing from a provider ID.
- Compare completed-task quality, latency, retries, allowance consumption, and cache reuse, not token price alone. Published benchmarks use other harnesses and do not establish a universal Pi ranking. Missing/zero Pi cost estimates do not mean free or unlimited usage. Supply provider and model together and inspect the returned effective execution profile.`;
